---
# tasks file for centos_packages
- name: Add repository file
  copy:
    src: "{{ src }}"
    dest: "{{ dest }}"
    mode: '0755'
  when: src != ""

- name: Install package using yum
  yum:
    name: "{{ package }}"
    state: latest
    update_cache: yes

- name: Start Service
  service:
    name: "{{ service }}"
    state: started
    enabled: yes
  when: service != ""
